name: add-bonus
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pycaret
  - ipykernel
  - seaborn
  - ydata-profiling
  - sweetviz
  - h2o-py
  - openjdk=11
  - nltk
  - rasterio
  - librosa
  - tensorflow
  - wordcloud
