name: add-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pandas
  - scipy
  - scikit-learn
  - seaborn
  - matplotlib
  - bs4
  - sqlalchemy
  - missingno
  - requests
  - ipykernel
  - imbalanced-learn
  - category_encoders
  - nltk
  - umap-learn